[package]
name = "tsukimi"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_12"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
async-channel = "2.2.0"
once_cell = "1.7.2"
lazy_static = "1.4.0"
lru = "0.12.3"
