name: Issue Feedback/Feature Request
description: Feedback issues or feature requests
title: "Issue Feedback/Feature Request"
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Ensure the following information
      description: Please confirm the following information
      options:
        - label: When reporting a bug, please attach the complete log, which usually starts with something like this. `2024-10-01T07:55:46.305728Z  INFO tsukimi: Application Version: 0.13.0, Platform: linux unix, CPU Architecture: x86_64`
          required: true
        
        - label: The method to obtain the log is to run the program in the terminal
          required: true

        - label: Repeated issues will be closed
          required: true

        - label: Please make sure you have read the FAQ and pinned issues before submitting
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe the problem you encountered in detail
    validations:
      required: true
