on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: tsukimi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libpango1.0-dev
        run: sudo apt install libgtk-4-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
